/* Four gentle stories: safe walking, a counting picnic, letters and planting. */
(() => {
  const shuffle=items=>items.slice().sort(()=>Math.random()-.5);
  window.MiniGames={start(game,kit){
    const {$,art,shell,speak,setVoice,message,guide,bindPick,returnTile,fly,celebrate,foodNames,flow}=kit;
    const bookAudioRemaining=()=>window.AdventureBook.audioRemaining();
    const toys=art.playthings,reduce=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
    const buttons=items=>items.map(([id,label])=>`<button class="learning-tool food-tile" data-pick="${id}" aria-label="${label}">${toys[id]}<span>${label}</span></button>`).join('');
    const modes=()=>'<nav class="learning-modes" aria-label="Choose difficulty"><button data-level="1" aria-label="Easy" aria-pressed="true">●</button><button data-level="2" aria-label="More choices" aria-pressed="false">● ●</button></nav>';
    function status(phase){$('new-game').dataset.phase=phase;}
    function flash(node){returnTile(node);}
    if(game==='traffic'){
      let round=0,step=0,phase='choose',token=0,route=[],motions=[];
      const places=['park','market','library'];
      shell('A Little Walk','',`<div class="toy-content route-content"><aside class="route-card"><div id="route-goal" class="route-goal"></div><div id="route-map" class="route-map" aria-label="Our path to the destination"></div><div class="round-dots" id="walk-progress"></div></aside><div class="traffic-work"><div class="traffic-scene" id="traffic-scene" data-signal="red"><div class="traffic-town" id="traffic-destination"></div><div class="traffic-road"><div class="crossing-stripes"></div><span class="road-car car-one">${art.vehicles.car}</span><span class="road-car car-two">${art.vehicles.bus}</span><span class="road-car car-turn">${art.vehicles.van}</span></div><div class="traffic-signal" id="traffic-signal">${toys.signal}</div><div class="traffic-walkers" id="traffic-walkers"><span class="grownup-walker">${art.grownup()}</span><span class="small-walker">${art.kid()}</span><span class="held-hands" aria-hidden="true"></span></div></div><div class="route-controls"><div id="route-choices" class="route-choices"><button id="route-left" data-turn="left" class="toy-button route-turn" aria-label="Choose the left route">${art.icons.left}</button><button id="route-right" data-turn="right" class="toy-button route-turn" aria-label="Choose the right route">${art.icons.right}</button></div><button id="cross-road" class="toy-button crossing-button" aria-label="Wait for green">${art.icons.hand}</button></div></div></div><footer class="toy-footer"><p id="toy-message" class="toy-message sr-only" role="status"></p><button id="walk-next" class="toy-button" aria-label="Next walk" hidden>${art.icons.play}</button></footer>`);
      function cancel(){token++;motions.forEach(a=>a.cancel());motions=[];flow.cancel();}
      function map(){
        const points=[[150,263],...route.map((d,i)=>[d==='left'? 70:230,198-i*74]),[150,43]];
        const line=points.slice(0,step+1).map(p=>p.join(',')).join(' '),current=points[Math.min(step,points.length-1)];
        $('route-map').innerHTML=`<svg viewBox="0 0 300 300" aria-hidden="true"><path d="M150 263L70 198L70 124L150 43M150 263L230 198L230 124L150 43M70 198L230 124M230 198L70 124" stroke="#d5dbc6" stroke-width="18" stroke-linecap="round" stroke-linejoin="round" fill="none"/><polyline points="${line}" stroke="#9bae7b" stroke-width="13" fill="none" stroke-linecap="round" stroke-linejoin="round"/>${[ [150,263],[70,198],[230,198],[70,124],[230,124],[150,43] ].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="10" fill="#f8f0d8" stroke="#acbb90" stroke-width="2"/>`).join('')}<circle id="route-marker" cx="${current[0]}" cy="${current[1]}" r="14" fill="#d7a36a"/></svg>`;
      }
      function render(){status(phase);$('new-game').dataset.round=round;$('new-game').dataset.step=step;$('new-game').dataset.route=route.join(',');$('traffic-scene').dataset.signal=['green','crossing','checkpoint','done'].includes(phase)?'green':'red';$('traffic-scene').dataset.phase=phase;
        $('route-goal').innerHTML=art.places[places[round]];$('traffic-destination').innerHTML=art.places[places[round]];
        $('walk-progress').innerHTML=places.map((_,i)=>`<i class="${i===round?'current':''}"></i>`).join('');$('route-choices').hidden=phase!=='choose';$('cross-road').hidden=phase==='choose'||phase==='done'||phase==='checkpoint';$('cross-road').innerHTML=phase==='green'||phase==='crossing'?art.icons.footsteps:art.icons.hand;$('cross-road').classList.toggle('walk-ready',phase==='green');$('cross-road').disabled=phase==='crossing';$('cross-road').setAttribute('aria-label',phase==='green'?'Walk with a grown-up':'Wait for green');map();
      }
      async function prepare(direction){
        if(phase!=='choose')return;if(direction)route.push(direction);phase='red';render();const own=token;
        if(direction)speak('traffic-turn-'+direction);else speak('traffic-wait');
        const width=$('traffic-scene').clientWidth,duration=reduce()?1400:2200;
        const cars=[...$('traffic-scene').querySelectorAll('.road-car')];cars.forEach(c=>c.style.opacity='1');
        const frames=[
          [{transform:`translateX(${-width*.7}px)`},{transform:`translateX(${-width*.31}px)`}],
          [{transform:`translateX(${width*.6}px)`},{transform:`translateX(${width*.13}px)`}],
          [{transform:`translate(${width*.45}px,-55px) rotate(0deg)`,opacity:1},{transform:'translate(0,-55px) rotate(0deg)',offset:.4,opacity:1},{transform:`translate(${-width*.5}px,-110px) rotate(35deg)`,opacity:0}]
        ];
        $('traffic-scene').dataset.carsStopped='false';motions=cars.map((car,i)=>car.animate(reduce()?[frames[i].at(-1),frames[i].at(-1)]:frames[i],{duration:duration+i*150,easing:'ease-out',fill:'forwards'}));
        await Promise.allSettled(motions.map(a=>a.finished));if(own!==token)return;
        $('traffic-scene').dataset.carsStopped='true';phase='green';render();speak('traffic-green');
      }
      function resetCrossing(){cancel();$('traffic-walkers').style.transform='';$('traffic-destination').classList.remove('celebrate');phase='choose';render();if(step===2)prepare();else setVoice(step?'traffic-next':'traffic-'+places[round]);}
      $('route-left').addEventListener('click',()=>prepare('left'));$('route-right').addEventListener('click',()=>prepare('right'));
      $('cross-road').addEventListener('click',async()=>{
        if(phase==='crossing')return;if(phase!=='green'||$('traffic-scene').dataset.carsStopped!=='true'){flash($('cross-road'));speak('traffic-wrong');return;}
        phase='crossing';render();speak('traffic-cross');const own=token,node=$('traffic-walkers'),distance=$('traffic-scene').clientHeight*.56;
        const a=node.animate([{transform:'translateY(0)'},{transform:`translateY(-${distance}px)`}],{duration:reduce()?1:1900,easing:'linear',fill:'forwards'});motions.push(a);try{await a.finished;}catch{return;}if(own!==token)return;
        step++;phase=step===3?'done':'checkpoint';render();celebrate(step===3?$('traffic-destination'):$('route-goal'));
        if(phase==='done'){speak('traffic-done');flow.after(()=>{round=(round+1)%places.length;step=0;route=[];resetCrossing();speak('traffic-'+places[round]);});}
        else{setVoice('traffic-next');flow.after(()=>{resetCrossing();if(step<2)speak('traffic-next');},Math.max(1900,bookAudioRemaining()));}
      });
      window.addEventListener('pagehide',cancel);document.addEventListener('visibilitychange',()=>motions.forEach(a=>{if(a.playState==='finished'||a.playState==='idle')return;if(document.hidden)a.pause();else a.play();}));resetCrossing();
    }else if(game==='counting'){
      let level=1,round=0,count=0,phase='play',busy=false,token=0;
      let targets=shuffle([1,2,3,4,5]);const friends=[['rabbit','carrot'],['monkey','banana'],['elephant','apple']];
      shell('A Counting Picnic','ONE LITTLE PIECE · ONE HAPPY FRIEND',`${modes()}<div class="toy-content picnic-content"><aside class="picnic-card"><p class="eyebrow">OUR PICNIC CARD</p><div id="picnic-friend" class="picnic-friend"></div><div class="picnic-order"><strong id="picnic-target"></strong><span id="picnic-food"></span></div><p id="picnic-request"></p><p id="picnic-round" class="toy-counter"></p></aside><div class="picnic-work"><div id="picnic-basket" class="picnic-basket" aria-label="Drop the food here"><div class="picnic-rug"></div><div id="picnic-pieces" class="picnic-pieces"></div><div class="picnic-count"><strong id="picnic-count">0</strong> little pieces</div><button id="picnic-remove" class="toy-button">Put one back ↶</button></div><div id="picnic-foods" class="picnic-foods"></div></div></div><footer class="toy-footer"><p id="toy-message" class="toy-message" role="status"></p><button id="picnic-check" class="toy-button">Count &amp; check ✓</button></footer>`);
      const target=()=>targets[round],friend=()=>friends[round%friends.length];
      function render(){status(phase);$('new-game').dataset.target=target();$('new-game').dataset.count=count;$('new-game').dataset.level=level;$('picnic-target').innerHTML=`<strong>${target()}</strong><span class="number-pips">${Array.from({length:target()},()=>'<i></i>').join('')}</span>`;$('picnic-friend').innerHTML=art.animals[friend()[0]];$('picnic-food').innerHTML=art.food[friend()[1]];$('picnic-request').textContent=`${foodNames[friend()[1]]} picnic · match the number`;$('picnic-round').textContent=`${round+1} / ${targets.length} picnic cards`;$('picnic-pieces').innerHTML=Array.from({length:count},()=>`<span>${art.food[friend()[1]]}</span>`).join('');$('picnic-count').textContent=count;$('picnic-remove').disabled=!count||busy||phase==='done';$('picnic-check').disabled=busy;$('picnic-check').textContent=phase==='done'?'Another picnic card →':'Count & check ✓';$('picnic-foods').querySelectorAll('button').forEach(b=>b.disabled=phase==='done');$('new-game').querySelectorAll('[data-level]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.level)===level));}
      function reset(){flow.cancel();token++;$('picnic-basket').classList.remove('celebrate');busy=false;count=0;phase='play';$('picnic-foods').innerHTML=['carrot','banana','apple','strawberry'].map(id=>`<button class="food-tile" data-pick="${id}">${art.food[id]}<span>${foodNames[id]}</span></button>`).join('');render();message(`Can you prepare ${target()} little pieces?`,'Tap food or drag it onto our picnic rug. One touch makes one piece.');setVoice(`number-${target()}`);}
      bindPick($('picnic-foods'),'#picnic-basket',async(id,node)=>{if(busy||phase!=='play')return;if(id!==friend()[1]||count>=target()){flash(node);message('Let us look at our picnic card.','Choose the pictured food and match its number.');speak('counting-wrong');return;}busy=true;const own=token;speak(`number-${count+1}`);await fly(node,$('picnic-basket'));if(own!==token)return;count++;busy=false;render();setVoice(`number-${target()}`);message(`${count} little ${count===1?'piece':'pieces'}.`,`Our picnic card asks for ${target()}.`);if(count===target())completePicnic();});
      $('picnic-remove').addEventListener('click',()=>{if(busy||phase!=='play'||!count)return;count--;render();message('One piece goes back.','We can always count and try again.');});
      function nextPicnic(){if(phase!=='done')return;round++;if(round===targets.length){round=0;targets=shuffle(level===1?[1,2,3,4,5]:[1,2,3,4,5,6,7,8,9,10]);}reset();speak(`number-${target()}`);}
      function completePicnic(){if(phase!=='play'||busy||count!==target())return;phase='done';render();CreatureMotion.play($('picnic-friend'),friend()[0]);celebrate($('picnic-basket'));speak('counting-done');flow.after(nextPicnic);}
      $('picnic-check').addEventListener('click',()=>{if(busy)return;if(phase==='done'){nextPicnic();return;}if(count!==target()){flash($('picnic-check'));speak('counting-wrong');return;}completePicnic();});
      $('new-game').querySelector('.learning-modes').addEventListener('click',e=>{const b=e.target.closest('button[data-level]');if(!b)return;level=Number(b.dataset.level);round=0;targets=shuffle(level===1?[1,2,3,4,5]:[1,2,3,4,5,6,7,8,9,10]);reset();speak(`number-${target()}`);});reset();
    }else if(game==='letters'){
      const words=['apple','banana','cow','duck','elephant','frog','giraffe','hippo','ice cream','jellyfish','kangaroo','lion','monkey','nest','otter','panda','queen','rabbit','strawberry','turtle','umbrella','vegetables','whale','xylophone','yo-yo','zebra'];
      const pictures=words.map(word=>art.animals[word]||art.food[word]||({ 'ice cream':toys.icecream,nest:toys.nest,queen:art.story,umbrella:toys.umbrella,vegetables:art.dishes.soup,xylophone:toys.xylophone,'yo-yo':toys.yoyo})[word]);
      let level=1,round=0,deck=shuffle([...Array(26).keys()]),phase='play',busy=false,token=0,drag;
      const letter=()=>String.fromCharCode(65+deck[round]);
      shell('The Letter Post','A LITTLE LETTER · A LOVELY DELIVERY',`${modes()}<div class="toy-content letter-content"><aside class="letter-card"><p class="eyebrow">TODAY'S PICTURE POSTCARD</p><div id="letter-picture" class="letter-picture"></div><h2 id="letter-word"></h2><div id="letter-delivery"><button id="letter-envelope" class="letter-envelope" aria-label="Drag this letter to its matching postbox">${toys.envelope}<strong id="envelope-letter"></strong></button></div><p id="letter-hint"></p><p id="letter-progress" class="toy-counter"></p></aside><div class="post-office"><div class="post-roof">ZOEY'S LITTLE POST</div><div id="letter-boxes" class="letter-boxes"></div><div class="post-stamps" id="post-stamps"></div>${guide()}</div></div><footer class="toy-footer"><p id="toy-message" class="toy-message" role="status"></p><button id="letter-next" class="toy-button" disabled>Another little letter →</button></footer>`);
      function cleanupDrag(){if(drag){drag.ghost?.remove();drag=null;}}
      function reset(){flow.cancel();token++;cleanupDrag();busy=false;phase='play';status(phase);$('new-game').dataset.letter=letter();$('new-game').dataset.level=level;$('letter-picture').innerHTML=pictures[deck[round]];$('letter-word').textContent=words[deck[round]];$('envelope-letter').textContent=letter();$('letter-envelope').disabled=false;$('letter-hint').textContent=level===1?'Find the same capital letter.':'Match our capital with its small letter.';$('letter-progress').textContent=`${round+1} / 26 letters`;$('letter-next').disabled=true;$('new-game').querySelectorAll('[data-level]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.level)===level));const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ',wrong=shuffle([...alphabet].filter(l=>l!==letter())).slice(0,2);$('letter-boxes').innerHTML=shuffle([letter(),...wrong]).map(l=>`<button class="letter-box" data-letter="${l}" aria-label="${level===1?'Capital':'Small'} ${l}"><span class="mail-slot"></span><strong>${level===1?l:l.toLowerCase()}</strong><span class="mail-door">✉</span></button>`).join('');$('post-stamps').innerHTML=Array.from({length:round%6},()=>'<span>✦</span>').join('');message('Where does our little letter belong?',level===1?'Match the shape of the capital letter.':'Big and small letters can be friends.');setVoice(`letter-${letter().toLowerCase()}`);}
      async function deliver(chosen,node){if(busy||phase!=='play')return;if(chosen!==letter()){flash(node);message('Almost! Try another postbox.','Look carefully at the letter shapes.');speak('letters-wrong');return;}busy=true;const own=token;speak('letters-done');await fly($('letter-envelope'),node);if(own!==token)return;busy=false;phase='done';status(phase);$('letter-envelope').disabled=true;$('letter-boxes').querySelectorAll('button').forEach(b=>b.disabled=true);node.classList.add('mail-delivered');$('letter-next').disabled=false;$('post-stamps').innerHTML+= '<span>✦</span>';celebrate(node);message(`${letter()} is for ${words[deck[round]]}.`,'A little letter, delivered with care.');setVoice(`letter-${letter().toLowerCase()}`);flow.after(nextLetter);}
      $('letter-boxes').addEventListener('click',e=>{const box=e.target.closest('button[data-letter]');if(box)deliver(box.dataset.letter,box);});
      const envelope=$('letter-envelope');envelope.addEventListener('pointerdown',e=>{if(busy||phase!=='play'||!e.isPrimary||e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,ghost:null};envelope.setPointerCapture(e.pointerId);e.preventDefault();});
      envelope.addEventListener('pointermove',e=>{if(drag?.id!==e.pointerId)return;if(!drag.ghost&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<8)return;if(!drag.ghost){drag.ghost=document.createElement('span');drag.ghost.className='drop-ghost';drag.ghost.innerHTML=toys.envelope+`<strong class="flying-letter">${letter()}</strong>`;document.body.append(drag.ghost);}drag.ghost.style.left=`${e.clientX-42}px`;drag.ghost.style.top=`${e.clientY-42}px`;e.preventDefault();});
      function end(e){if(drag?.id!==e.pointerId)return;const moved=!!drag.ghost;cleanupDrag();if(envelope.hasPointerCapture(e.pointerId))envelope.releasePointerCapture(e.pointerId);if(e.type==='pointercancel')return;if(!moved){speak(`letter-${letter().toLowerCase()}`);return;}const box=[...$('letter-boxes').querySelectorAll('button')].find(n=>{const r=n.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom;});if(box)deliver(box.dataset.letter,box);else flash(envelope);}
      envelope.addEventListener('pointerup',end);envelope.addEventListener('pointercancel',end);envelope.addEventListener('lostpointercapture',cleanupDrag);envelope.addEventListener('click',e=>{if(e.detail===0)speak(`letter-${letter().toLowerCase()}`);});
      function nextLetter(){if(phase!=='done')return;round++;if(round===26){round=0;deck=shuffle([...Array(26).keys()]);}reset();speak(`letter-${letter().toLowerCase()}`);}$('letter-next').addEventListener('click',nextLetter);$('new-game').querySelector('.learning-modes').addEventListener('click',e=>{const b=e.target.closest('button[data-level]');if(!b)return;level=Number(b.dataset.level);reset();speak(`letter-${letter().toLowerCase()}`);});window.addEventListener('pagehide',()=>{cleanupDrag();token++;});reset();
    }else if(game==='seedling'){
      let size=1,phase='dig',digs=0,seeds=0,water=0,busy=false,token=0,timer;
      const sequence=['dig','seed','cover','water','sun'],correct={dig:'spade',seed:'seed',cover:'soil',water:'water',sun:'sun'},names={dig:'挖一个小坑',seed:'放进小种子',cover:'盖上薄薄的土',water:'轻轻浇两次水',sun:'请太阳来帮忙',growing:'小花正在长大',done:'小花开啦！'};
      shell('挖呀种花园','中文小故事 · 一颗种子的旅行',`<nav class="learning-modes garden-sizes" aria-label="选择花园大小"><button data-size="1" aria-pressed="true" aria-label="小花园">1</button><button data-size="3" aria-pressed="false" aria-label="中花园">3</button><button data-size="5" aria-pressed="false" aria-label="大花园">5</button></nav><div class="toy-content seedling-content"><aside class="seedling-card"><p class="eyebrow">小园丁的种花计划</p><ol id="seedling-plan"></ol>${guide()}<p class="seedling-fact">小花长大需要适量的水、阳光和时间。<br>每种植物长大的速度都不一样。</p></aside><div class="seedling-work"><button id="garden-bed" class="garden-bed" aria-label="花园：轻点来完成当前的种花步骤"><span class="garden-sky"><span id="garden-sun">${toys.sun}</span><span class="garden-cloud"></span></span><span class="garden-earth"></span><span id="garden-holes" class="garden-holes"></span><span id="garden-plants" class="garden-plants"></span><span id="garden-actor" class="garden-actor"></span><span id="garden-caption" class="garden-caption"></span><span class="garden-rain" id="garden-rain" hidden></span></button><div id="garden-tools" class="garden-tools">${buttons([['spade','小铲子'],['seed','种子'],['soil','盖土'],['water','浇水壶'],['sun','太阳']])}</div></div></div><footer class="toy-footer"><p id="toy-message" class="toy-message" role="status"></p><button id="seedling-again" class="toy-button" disabled>再种一次 ↻</button></footer>`);
      $('new-game').lang='zh-CN';$('toy-listen').setAttribute('aria-label','听 Zoey 讲');
      function render(){status(phase);$('new-game').dataset.size=size;$('new-game').dataset.digs=digs;$('new-game').dataset.seeds=seeds;$('new-game').dataset.water=water;$('garden-bed').dataset.phase=phase;$('garden-bed').disabled=busy||phase==='growing'||phase==='done';$('seedling-again').disabled=phase!=='done';$('garden-caption').textContent=names[phase]+(phase==='dig'?` · ${digs}/3`:phase==='seed'?` · ${seeds}/${size}`:phase==='water'?` · ${water}/2`:'');const current=sequence.indexOf(phase);$('seedling-plan').innerHTML=sequence.map((p,i)=>`<li class="${phase==='done'||phase==='growing'||i<current?'step-done':i===current?'step-current':''}">${toys[correct[p]]}<span class="sr-only">${names[p]}</span></li>`).join('');$('garden-holes').innerHTML=Array.from({length:size},(_,i)=>`<span class="garden-hole" style="left:${(i+1)*100/(size+1)}%;opacity:${digs/3}">${seeds>i&&phase!=='cover'&&phase!=='seed'?'':seeds>i?toys.seed:''}</span>`).join('');$('garden-plants').innerHTML=Array.from({length:phase==='growing'||phase==='done'?size:0},(_,i)=>`<span class="garden-flower" style="width:${Math.min(38,85/size)}%;left:${(i+1)*100/(size+1)}%;--flower-delay:${i*110}ms;--flower-hue:${i*27}deg">${toys.flower}</span>`).join('');$('garden-plants').querySelectorAll('svg').forEach(svg=>svg.setAttribute('preserveAspectRatio','xMidYMax meet'));$('garden-tools').querySelectorAll('[data-pick]').forEach(b=>{b.disabled=phase==='growing'||phase==='done';b.classList.toggle('next-ingredient',b.dataset.pick===correct[phase]);});$('new-game').querySelectorAll('[data-size]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.size)===size));}
      function reset(){flow.cancel();token++;clearTimeout(timer);$('garden-bed').classList.remove('celebrate');busy=false;phase='dig';digs=0;seeds=0;water=0;$('garden-rain').hidden=true;$('garden-actor').innerHTML='';render();message('一颗种子，会长成什么呢？','先用小铲子挖三下。可以点工具，也可以拖进花园。');setVoice('seedling-intro');}
      async function use(id,node){if(busy||phase==='growing'||phase==='done')return;if(id!==correct[phase]){flash(node);message('先等等，下一步是：'+names[phase]+'。','小园丁可以慢慢来，再试一次。');speak('seedling-wrong');return;}busy=true;const own=token;$('garden-actor').innerHTML=toys[id];PlaythingMotion.play($('garden-actor'),id);if(node!==$('garden-bed'))await fly(node,$('garden-bed'));else await new Promise(r=>setTimeout(r,reduce()?1:250));if(own!==token)return;busy=false;
        if(phase==='dig'){digs++;if(digs===3){phase='seed';speak('seedling-seed');}else speak('seedling-dig');}
        else if(phase==='seed'){seeds++;if(seeds===size){phase='cover';speak('seedling-cover');}else speak(size===3?'seedling-medium':'seedling-large');}
        else if(phase==='cover'){phase='water';speak('seedling-water');}
        else if(phase==='water'){water++;$('garden-rain').hidden=false;setTimeout(()=>{if(own===token)$('garden-rain').hidden=true;},750);if(water===2){phase='sun';speak('seedling-sun');}else speak('seedling-water');}
        else if(phase==='sun'){phase='growing';speak('seedling-fact');timer=setTimeout(()=>{if(own!==token)return;phase='done';$('garden-actor').innerHTML='';render();celebrate($('garden-bed'));message(`开花啦！你种出了 ${size} 朵漂亮的花。`,'谢谢你细心照顾。真实的小花要等很多天，慢慢长大。');speak('seedling-done');flow.after(()=>{reset();speak('seedling-intro');});},Math.max(2600,AdventureBook.audioRemaining()));}
        render();if(phase!=='growing')message(names[phase],phase==='seed'?`还需要 ${size-seeds} 颗种子。`:'按顺序照顾它，看看小花的变化。');else message('小花正在长大……','游戏里时间走得很快，真实植物要慢慢等。');
      }
      bindPick($('garden-tools'),'#garden-bed',use);$('garden-bed').addEventListener('click',()=>use(correct[phase],$('garden-bed')));$('seedling-again').addEventListener('click',()=>{if(phase==='done'){reset();speak('seedling-intro');}});$('new-game').querySelector('.garden-sizes').addEventListener('click',e=>{const b=e.target.closest('button[data-size]');if(!b)return;size=Number(b.dataset.size);reset();speak(size===1?'seedling-small':size===3?'seedling-medium':'seedling-large');});window.addEventListener('pagehide',()=>{clearTimeout(timer);token++;});reset();
    }
  }};
})();
